config/routes.rb
Crowdfunder::Application.routes.draw do

  root :to => 'projects#index'

  resources :user_sessions
  resources :users
  resources :projects do
    resources :pledges, :except => [:index]
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :pledges
	has_many :users, :through => :pledges

	validates_presence_of :name
	validates_presence_of :description
	validates_numericality_of :goal

	def current_project
		project = Project.id
		Pledge.where( :project_id => project.id ).where( :user_id => user.id )
	end

	def formatted_price
    	price_in_dollars = goal.to_f / 100
    	sprintf("%.2f", price_in_dollars)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :pledges
	has_many :projects, :through => :pledges

	authenticates_with_sorcery!

	validates :password, length: { minimum: 3 }
	validates :password, confirmation: true
	validates :password_confirmation, presence: true
	
	validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  #def current_project
  #project = Project.id
  #	Pledge.where( :project_id => project.id ).where( :user_id => user.id )
  #end
  
  #helper_method :current_project

  private
  def not_authorized
  	redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_filter :load_project

  def show
  	@pledge = Pledge.find(params[:id])
  end

  def create
  	@pledge = @project.pledges.build(pledge_params)
  	@pledge.user_id = current_user.id
  
    respond_to do |format|
  	  if @pledge.save
  	   	format.html { redirect_to project_path(@project.id), notice: 'Pledged!' }
        format.js {}
  	  else
  	   	format.html { render :action => :show }
        format.js {}
  	  end
    end
  end

  private
  def load_project
  	@project = Project.find(params[:project_id])
  end

  def pledge_params
  	params.require(:pledge).permit(:amount, :project_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper :all
  skip_before_filter :require_login, except: [:edit, :new, :create, :destroy]
 
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_url
    else 
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def show
    @project = Project.find(params[:id])

    if current_user
      @pledge = @project.pledges.build
    end
  end

  def index
    @projects = Project.all
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :description, :goal, :starttime, :endtime)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  
  def new
  	@user = User.new
  end

  def create
  	if @user = login(params[:email], params[:password])
  		redirect_back_or_to(root_path, notice: 'Login successful')
  	else
  		flash.now[:alert] = "Login failed"
  		render action: "new"
  	end
  end

  def destroy
  	logout
  	redirect_to(root_path, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to(root_path, notice: 'User was successfully created.') }
        format.json { render action: 'projects', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Codfunder" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Codfunder", root_url %></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
        <% if current_user %>
          <li><%= link_to "Profile", user_path(current_user.id) %></li>
          <li><%= link_to "Logout", :logout, method: :post %></li>
        <% else %> 
          <li><%= link_to "Register", new_user_path %> </li>
          <li><%= link_to "Login", :login %></li>
        <% end %>
    </ul>

    <ul class="left">
      <li><%= link_to 'New Project', 'projects/new' %></li>
    </ul>
  </section>
</nav>

    <div class="container">
      <div>
        <% if flash[:notice] %>
          <div class="notice"><%= flash[:notice] %></div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert"><%= flash[:alert] %></div>
        <% end %>
      </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
    </div>
  </body>
</html>

app/views/pledges/_pledge_form.html.erb
<% if current_user %>
<h3>Pledge for <%= @project.name %></h3>

<%= form_for [@project, @pledge] do |f| %>
	
	<% if @pledge.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being made:</h2>
			<ul>
			<% @pledge.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="large-4 columns">
		<%= f.label :amount %><br />
		<%= f.number_field :amount, :min => 1 %>
	</div><hr/>
	<div class="action">
		<button class="button [radius round]">Create Pledge</button>
	</div>
<% end %>

	<% else %>
		<p>Please <%= link_to 'log in', new_user_session_path %> to pledge</p>
	<% end %>

app/views/pledges/_pledge_form_errors.html.erb
  <div id="pledge-form-errors">
    <% if @pledge.errors.present? %>
      <% @pledge.errors.full_messages.each do |error| %>
        <div class="alert">
          <%= error %>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/pledges/create.js.erb
<% if @pledge.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/pledges/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#total-pledges").html("<%= escape_javascript(render(:partial => 'total_pledges')) %>");
  $("#new_pledge")[0].reset();
<% end %>

app/views/pledges/new.html.erb
<h1>Pledges#new</h1>
<p>Find me in app/views/pledges/new.html.erb</p>

app/views/pledges/show.html.erb
<h1>Pledges#show</h1>
<p>Find me in app/views/pledges/show.html.erb</p>

app/views/projects/_form.html.erb
<%= form_for (@project) do |f| %>

	<% if @project.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@project.errors.count, "error") %>
				prohibited this project from being saved:</h2>

				<ul>
					<% @project.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label "name" %>
		<%= f.text_field "name" %>
	</div>
	<div class="field">
		<%= f.label "description" %>
		<%= f.text_area "description" %>
	</div>
	<div class="field">
		<%= f.label "goal" %>
		<%= f.number_field "goal" %>
	</div>
	<div class="field" id="date">
		<%= f.label "start time" %>
		<%= f.date_select "starttime" %>
	</div>
	<div class="field" id="date">
		<%= f.label "end time" %>
		<%= f.date_select "endtime" %>
	</div>
	<div class="actions">
		<%= f.submit "Save" %>
	</div>
<% end %>

app/views/projects/_total_pledges.html.erb
<h2>Total Pledged:</h2> <h4><%= number_to_currency(@project.pledges.sum(:amount)) %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<%= link_to 'Home', projects_path %>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1> Projects </h1>

<div class="panel callout radius">
<h3>Total Funded For All Projects: <%= number_to_currency(Pledge.all.sum(:amount)) %></h3>
</div>

<% @projects.each do |project| %>
	<h3><%= link_to project.name, project %></h3>
  <hr/>
<% end %>

app/views/projects/show.html.erb
<h1>
	<%= @project[:name] %>
</h1>
	<hr/>
<div style="word-wrap: break-word;">
	<h2>About This Project:</h2><br/><p> <%= @project[:description] %></p>
	<hr/>
	<h2>Project Goal:</h2></br> <h3><%= number_to_currency(@project.goal) %></h3>
	<hr/>
	</p>
  <div class="total-pledges">
	  <%= render :partial => 'total_pledges' %>
  </div>
</div>

<p><% time_diff_components = Time.diff(@project[:starttime], @project[:endtime]) %>
   Number of Days Left: <%= time_diff_components[:day] %> </h4>
</p>

<% if Time.now <= @project[:endtime] %>

<div id="pledge-form-errors">
  <%= render :partial => "pledges/pledge_form_errors" %>
</div>

<%= render 'pledges/pledge_form' %>

<% else %>
<p>This project has ended! </p>
<% end %>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/user_sessions/_form.html.erb
	<fieldset>
		<legend><h1>Log in</h1></legend>
			<%= form_tag user_sessions_path, :method => :post do %>
				<div class="field">
					<%= label_tag :email %><br />
					<%= text_field_tag :email %>
				</div>
				<div class="field">
					<%= label_tag :password %><br />
					<%= password_field_tag :password %>
				</div>
				<div class="actions">
					<button class="button [radius round]">Log in</button>
				</div>
			<% end %>	
	</fieldset>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<%= render 'form' %>

app/views/users/_form.html.erb
  <fieldset>
    <legend><h1>Sign up</h1></legend>
      <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="actions">
        <button class="button [radius round]">Create Account</button>
      </div>
    <% end %>
  </fieldset>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Home', projects_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <hr />
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Home', projects_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<hr />
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<div class="large-6 medium-6 small-12 columns">
  <h2>My Pledges</h2>
    <% x = 1 %>
    <table class="my-pledges">        
      <thead> <td></td> <td>Project Name </td> <td>Amount Pledged</td> </thead>
      <% @user.pledges.each do |pledge| %>
        <% project = Project.where(:id => pledge.project_id) %>
        <% project.each do |proj| %>
          <tr>
              <td><%= x %></td>
              <td><%= link_to proj.name, project_path %></td>
              <td><%= number_to_currency(pledge.amount) %>
            <% end %>
          </tr>
        <% x+=1 %>
      <% end %>
    </table>
  </div>
<hr />
<%= link_to 'Edit', edit_user_path(@user) %>